/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "tertiary-fixed": "#d7e3ff",
                "surface-container-highest": "var(--color-surface-container-highest, #dde4e6)",
                "surface-gray": "var(--color-surface-gray, #F5F5F7)",
                "on-primary-container": "#fff7f5",
                "on-secondary-container": "#364d83",
                "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
                "surface-container": "var(--color-surface-container, #e8eff1)",
                "surface-container-low": "var(--color-surface-container-low, #eef5f7)",
                "surface-container-high": "var(--color-surface-container-high, #e2e9ec)",
                "secondary": "#001F54",
                "on-background": "var(--color-on-background, #161d1f)",
                "on-error-container": "#93000a",
                "on-secondary-fixed-variant": "#2e457b",
                "surface-tint": "#c00000",
                "on-secondary": "#ffffff",
                "tertiary": "#0058b1",
                "pulse-red-light": "#FFEBEE",
                "inverse-on-surface": "var(--color-inverse-on-surface, #ebf2f4)",
                "on-surface-variant": "var(--color-on-surface-variant, #5f3f3a)",
                "outline-variant": "var(--color-outline-variant, #e9bcb5)",
                "on-tertiary": "#ffffff",
                "primary-fixed-dim": "#ffb4a8",
                "outline": "var(--color-outline, #946e68)",
                "background": "var(--color-background, #f4fafd)",
                "on-primary-fixed-variant": "#930100",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#aac7ff",
                "on-primary": "#ffffff",
                "on-error": "#ffffff",
                "surface-bright": "var(--color-surface-bright, #f4fafd)",
                "inverse-primary": "#ffb4a8",
                "background-white": "var(--color-background-white, #FFFFFF)",
                "surface-variant": "var(--color-surface-variant, #dde4e6)",
                "surface-dim": "var(--color-surface-dim, #d4dbdd)",
                "primary-container": "#e60000",
                "primary-fixed": "#ffdad4",
                "secondary-fixed": "#dae2ff",
                "tertiary-container": "#1d70d7",
                "on-surface": "var(--color-on-surface, #161d1f)",
                "on-tertiary-container": "#f7f8ff",
                "on-tertiary-fixed-variant": "#00458e",
                "secondary-container": "#a9c0fe",
                "on-secondary-fixed": "#001946",
                "primary": "#E60000",
                "secondary-fixed-dim": "#b1c5ff",
                "on-tertiary-fixed": "#001b3e",
                "error": "#ba1a1a",
                "on-primary-fixed": "#410000",
                "inverse-surface": "var(--color-inverse-surface, #2b3234)",
                "medical-teal": "var(--color-primary, #176BCE)",
                "charcoal": "var(--color-charcoal, #2D3436)",
                "alert-red": "#E71D36",
                "signal-green": "#2ECC71",
                "brand-red": "#E60000",
                "brand-navy": "var(--color-brand-navy, #001F54)",
                "clinical-blue": "var(--color-primary, #176BCE)",
                "clinical-red": "#CE2A2B",
                "clinical-charcoal": "#2C2C2C",
                "clinical-surface": "#F2F2F2",
                "luxury-navy": "#071A3A",
                "luxury-muted": "#123B6D",
                "luxury-gold": "#F0C04A",
                "luxury-cream": "#F7F7F2",
                "luxury-slate": "#98A2B3"
            },
            fontFamily: {
                sans: ["Inter", "sans-serif"],
                "mono-data": ["monospace"],
                "body-lg": ["Inter", "sans-serif"],
                "headline-lg-mobile": ["Outfit", "sans-serif"],
                "label-md": ["Outfit", "sans-serif"],
                "headline-md": ["Outfit", "sans-serif"],
                "body-sm": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "headline-xl": ["Outfit", "sans-serif"],
                "headline-lg": ["Outfit", "sans-serif"],
                "luxury-headline": ["Playfair Display", "serif"],
                "luxury-button": ["Montserrat", "sans-serif"],
                "luxury-body": ["Lato", "sans-serif"],
            },
            spacing: {
                "margin-desktop": "48px",
                "margin-mobile": "16px",
                "container-max": "1280px",
                "gutter": "24px"
            },
            fontSize: {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "label-md": ["14px", {"lineHeight": "16px", "fontWeight": "600", "letterSpacing": "0.02em"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}]
            },
            transitionDuration: {
                "600": "600ms",
                "1500": "1500ms",
                "2000": "2000ms",
                "2400": "2400ms",
                "3000": "3000ms"
            },
            transitionTimingFunction: {
                "spring": "cubic-bezier(0.175, 0.885, 0.32, 1.275)"
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
        require('tailwindcss-animate')
    ],
}